
##--------------------------------------------------------------------
## General
##--------------------------------------------------------------------

##--------------------------------------------------------------------
## Task
##--------------------------------------------------------------------
#Concurrent task count for global task executor.
task.exec_workers = 2000
#Queue capacity for global task executor.
task.exec_queue_max = 300_000

##--------------------------------------------------------------------
## Node
##--------------------------------------------------------------------
#Node id
node.id = 1

#Busy status check switch.
#default value: true
node.busy.check_enable = true
#Busy status update interval.
#default value: 2s
node.busy.update_interval = "2s"
#The threshold for the 1-minute average system load used to determine system busyness.
#Value range: 0.0-100.0, default value: 80.0
node.busy.loadavg = 80.0
#The threshold for average CPU load used to determine system busyness.
#Value range: 0.0-100.0, default value: 90.0
node.busy.cpuloadavg = 90.0
#The threshold for determining high-concurrency connection handshakes in progress.
node.busy.handshaking = 0

##--------------------------------------------------------------------
## RPC
##--------------------------------------------------------------------
#gRPC listening address
rpc.server_addr = "0.0.0.0:5363"
#Number of worker threads
rpc.server_workers = 4


##--------------------------------------------------------------------
## Log
##--------------------------------------------------------------------
# Value: off | file | console | both
log.to = "both"
# Value: trace, debug, info, warn, error
log.level = "info"
log.dir = "./log"
log.file = "rmqtt.log"


##--------------------------------------------------------------------
## Plugins
##--------------------------------------------------------------------
#Plug in configuration file directory
plugins.dir = "./etc/plugins"
#Plug in started by default, when the mqtt server is started
plugins.default_startups = [
    #"rmqtt-plugin-template",
    #"rmqtt-retainer",
    #"rmqtt-auth-http",
    #"rmqtt-cluster-broadcast",
    #"rmqtt-cluster-raft",
    #"rmqtt-sys-topic",
    #"rmqtt-message-storage",
    #"rmqtt-session-storage",
    #"rmqtt-bridge-ingress-mqtt",
    #"rmqtt-bridge-egress-mqtt",
    #"rmqtt-bridge-ingress-kafka",
    #"rmqtt-bridge-egress-kafka",
    #"rmqtt-topic-rewrite",
    #"rmqtt-auto-subscription",
    #"rmqtt-bridge-egress-pulsar",
    #"rmqtt-bridge-ingress-pulsar",
    #"rmqtt-auth-jwt",
    #"rmqtt-bridge-egress-nats",
    #"rmqtt-bridge-egress-reductstore",
    "rmqtt-web-hook",
    "rmqtt-http-api"
]

##--------------------------------------------------------------------
## Listeners
##--------------------------------------------------------------------

##--------------------------------------------------------------------
## MQTT/TCP - External TCP Listener for MQTT Protocol
listener.tcp.external.addr = "0.0.0.0:52000"

#Number of worker threads (currently unused)
listener.tcp.external.workers = 8

#The maximum number of concurrent connections allowed by the listener.
listener.tcp.external.max_connections = 1024000

#Maximum concurrent handshake limit, Default: 500
listener.tcp.external.max_handshaking_limit = 500

#Handshake timeout.
listener.tcp.external.handshake_timeout = "30s"

#Maximum allowed mqtt message length. 0 means unlimited, default: 1m
listener.tcp.external.max_packet_size = "1m"

#The maximum length of the TCP connection queue.
#It indicates the maximum number of TCP connection queues that are being handshaked three times in the system
listener.tcp.external.backlog = 1024

#Sets the value of the TCP_NODELAY option on this socket.
#default: false
listener.tcp.external.nodelay = false

#Whether anonymous login is allowed. Default: false
listener.tcp.external.allow_anonymous = true

#A value of zero indicates disabling the keep-alive feature, where the server
#doesn't need to disconnect due to client inactivity, default: true
listener.tcp.external.allow_zero_keepalive = true

#Minimum allowable keepalive value for mqtt connection,
#less than this value will reject the connection(MQTT V3),
#less than this value will set keepalive to this value in CONNACK (MQTT V5),
#default: 0, unit: seconds
listener.tcp.external.min_keepalive = 0

#Maximum allowable keepalive value for mqtt connection,
#greater than this value will reject the connection(MQTT V3),
#greater than this value will set keepalive to this value in CONNACK (MQTT V5),
#default value: 65535, unit: seconds
listener.tcp.external.max_keepalive = 65535

# > 0.5, Keepalive * backoff * 2
listener.tcp.external.keepalive_backoff = 0.75

#Flight window size. The flight window is used to store the unanswered QoS 1 and QoS 2 messages
listener.tcp.external.max_inflight = 16

#Maximum length of message queue
listener.tcp.external.max_mqueue_len = 1000

#The rate at which messages are ejected from the message queue,
#default value: "u32::max_value(),1s"
listener.tcp.external.mqueue_rate_limit = "1000,1s"

#Maximum length of client ID allowed, Default: 65535
listener.tcp.external.max_clientid_len = 65535

#The maximum QoS level that clients are allowed to publish. default value: 2
listener.tcp.external.max_qos_allowed = 2

#The maximum level at which clients are allowed to subscribe to topics.
#0 means unlimited. default value: 0
listener.tcp.external.max_topic_levels = 0

#Session timeout, default value: 2 hours
listener.tcp.external.session_expiry_interval = "2h"

#The upper limit for how long a session can remain valid before it must expire,
#regardless of the client's requested session expiry interval
#default value: 0 hours (unlimited)
listener.tcp.external.max_session_expiry_interval = "0h"

#QoS 1/2 message retry interval, 0 means no resend
listener.tcp.external.message_retry_interval = "20s"

#Message expiration time, 0 means no expiration
listener.tcp.external.message_expiry_interval = "5m"

#The maximum number of topics that a single client is allowed to subscribe to
#0 means unlimited, default value: 0
listener.tcp.external.max_subscriptions = 0

#Shared subscription switch, default value: true
listener.tcp.external.shared_subscription = true

#topic alias maximum, default value: 0, topic aliases not enabled. (MQTT 5.0)
listener.tcp.external.max_topic_aliases = 32

#Limit subscription switch, default value: false
listener.tcp.external.limit_subscription = false

#Delayed publish switch, default value: false
listener.tcp.external.delayed_publish = false

##--------------------------------------------------------------------
## Internal TCP Listener for MQTT Protocol
listener.tcp.internal.enable = true
listener.tcp.internal.addr = "0.0.0.0:11883"
listener.tcp.internal.workers = 4
listener.tcp.internal.max_connections = 102400
listener.tcp.internal.max_handshaking_limit = 500
listener.tcp.internal.handshake_timeout = "30s"
listener.tcp.internal.max_packet_size = "1M"
listener.tcp.internal.backlog = 512
listener.tcp.internal.nodelay = false
listener.tcp.internal.allow_anonymous = false
listener.tcp.internal.allow_zero_keepalive = true
listener.tcp.internal.min_keepalive = 0
listener.tcp.internal.max_keepalive = 65535
listener.tcp.internal.keepalive_backoff = 0.75
listener.tcp.internal.max_inflight = 16
listener.tcp.internal.max_mqueue_len = 1000
listener.tcp.internal.mqueue_rate_limit = "1000,1s"
listener.tcp.internal.max_clientid_len = 65535
listener.tcp.internal.max_qos_allowed = 2
listener.tcp.internal.max_topic_levels = 0
listener.tcp.internal.session_expiry_interval = "2h"
listener.tcp.internal.max_session_expiry_interval = "0h"
listener.tcp.internal.message_retry_interval = "20s"
listener.tcp.internal.message_expiry_interval = "5m"
listener.tcp.internal.max_subscriptions = 0
listener.tcp.internal.shared_subscription = true
listener.tcp.internal.max_topic_aliases = 0
listener.tcp.internal.limit_subscription = false
listener.tcp.internal.delayed_publish = false

##--------------------------------------------------------------------
## MQTT/TLS - External TLS Listener for MQTT Protocol
#listener.tls.external.addr = "0.0.0.0:8883"
#listener.tls.external.cert = "./rmqtt-bin/rmqtt.pem"
#listener.tls.external.key = "./rmqtt-bin/rmqtt.key"


